FORMAT: 1A
HOST: http://api.theNoisyCity.com/

# The Noisy City

Close your eyes and listen to the noisy city.

## Enums

Enums in this project use `Int` as its base class, while generally won't use `0` or any number below 0`.

#### Channel

User can determine which channel to listen. Current avaliable channels are:

+ `1` **TA声与TA生  Voices from Him/her** very close, recent
+ `2` **繁华与喧闹  Voices from Around** close, very recent, random
+ `3` **他乡与故知  Voices from Hometown** far, recent
+ `4` **新街与旧闻  Voices from Localfolks** Folks from where you are, while far away from home
+ `5` **过往与当下  Voices from Past** same day in last year

#### Language

Sould we make Cantonese a language instead of a dialect?

+ `1` **Madarin**
+ `2` **Cantonese** Just a placeholder
+ `3` **English** Not available now

#### Report Reason

+ `1` **Rude**
+ `2` **Pornographic**
+ `3` **Meaningless**

## Database Tables

#### User

In `MySQL`

+ `uid` `primary key`
+ `username` its a nickname, can be edited, but not within a short period
+ `password` encrypted password, maybe with bcrypt
+ `email`
+ `email_confirmed` `bool`
+ `phone`
+ `phone_confirmed` `bool`
+ `create_time` all the time we store in database should be timestamp
+ `last_time_username_changed` timestamp
+ `language_first` mother tongue, see Language under Enums
+ `language_second`
+ `dialect_first` `geopoint`
+ `dialect_second` `geopoint`

#### Record

In `OSS`

+ `rid` `primary key`
+ `create_user`
+ `create_time`
+ `duration`
+ `upload_position`
+ `language`
+ `dialect` `geopoint`
+ 

#### Report

in `MySQL`

+ `report_id` `primary key`
+ `rid`
+ `reporter`
+ `reportee`
+ `report_time` `timestamp`
+ `reason`


## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }