FORMAT: 1A
HOST: http://api.theNoisyCity.com/

# The Noisy City

Close your eyes and listen to the noisy city.

## Enums

Enums in this project use `Int` as its base class, while generally won't use `0` or any number below 0`.

####Channels

User can determine which channel to listen. Current avaliable channels are:

+ `1` **TA声与TA生  Voices from Him/her** very close, recent
+ `2` **繁华与喧闹  Voices from Around** close, very recent, random
+ `3` **他乡与故知  Voices from Hometown** far, recent
+ `4` **新街与旧闻  Voices from Localfolks** Folks from where you are, while far away from home
+ `5` **过往与当下  Voices from Past** same day in last year



## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }